### ISSUE TITLE
Move in-speech stage directions

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaNLP#56]
Currently, the stage directions that are included in character speech are exported to the `UtterancesWith Tokens.csv` table. They should be removed from there and moved to the new `StageDirections.csv` table.

**Comment by pagelj** [comment]
The stage directions that are directly part of the character speech are usually marked by `<hi>...</hi>`. A possibility would be to find these occurrences and classify them as stage directions.

**Comment by pagelj** [comment]
In `rjmw.0`, there is an `<hi>Aber</hi>` in Marwoods character speech that currently gets falsely analysed as stage direction. Very likely, there are other such examples.

**Comment by nilsreiter** [comment]
This is also not fixed in gerdracor: https://github.com/dracor-org/gerdracor/blob/master/tei/lessing-miss-sara-sampson.xml has occurrences of `<hi>` as [stage direction](https://github.com/dracor-org/gerdracor/blob/d94f7a733e1e8285ae197bf2cf6858c00a48c2db/tei/lessing-miss-sara-sampson.xml#L4089) and [emphasis](https://github.com/dracor-org/gerdracor/blob/d94f7a733e1e8285ae197bf2cf6858c00a48c2db/tei/lessing-miss-sara-sampson.xml#L3681)

**Comment by nilsreiter** [comment]
It's fixed there now.

**Comment by pagelj** [comment]
We either correct the markings of such stage directions directly in the data ourselves or use the corrected GerDraCor version
