### ISSUE TITLE
Processing declaration of drama ending

### ISSUE THREAD

**Issue by pagelj** [quadrama/DramaNLP#59]
Often a drama ends with a declaration of the ending, like "Ende des Trauerspiels" etc. This declaration is usually marked with `<p>...</p>` in GerDraCor and not specially signalized further (i.e. also no marking a la `<hi>...</hi>` etc.). Hence it is currently part of the character speech. It might be nice to detect such occurrences automatically using heuristics and assign the `<stage>` (edit: better use `<trailer>`) tag to them.

**Comment by nilsreiter** [comment]
There might also be specific TEI vocabulary for that.

**Comment by pagelj** [comment]
TEI appears to use `<trailer>...</trailer>` for these kind of things (https://tei-c.org/release/doc/tei-p5-doc/en/Guidelines.pdf Version 3.5.0, p. 170-171, p. 235)

**Comment by nilsreiter** [comment]
The question is whether we really want to go into the TEI business. Might be easier to just tag it as `<stage>`, so that it's not character speech.

**Comment by pagelj** [comment]
It is not really stage directions either, though. So as soon as we want to do something with the stage directions we would want to have it out of there as well

**Comment by nilsreiter** [comment]
Let's coordinate this with @lehkost. In [GerDraCor's Emilia Galotti](https://github.com/dracor-org/gerdracor/blob/0cdf5f3f29b8fc2759b737d60584ab1ff6f94c60/tei/lessing-emilia-galotti.xml#L4850), it's marked as `<stage>` (our fork is apparently outdated here). Are there plans to change this? Our suggestion would be to use [`<trailer>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-trailer.html) instead.

**Comment by lehkost** [comment]
Hi both, thanks for roping me in. 😊 I definitely do think that we have to "go into the TEI business" as Nils put it, especially in regard to the TextGrid repo. The TEI conversion from zeno.org data has especially harmed the plays/dramas (the markup is adventurous to say the least, most stage directions not marked as such, there's missing text and an overhead of unneeded markup bloats everything). In the past 1,5 years, we've been doing repair work as is detailed in our GerDraCor wiki [here](https://github.com/dracor-org/gerdracor/wiki/Documentation-for-Correcting-Plays-from-TextGrid-Repository). Work's still not finished and I propose to wait until it's done (probably in April or May 2019) before updating your base. By then, we will also have a trimmed-down schema that actually conveys a realistic and to-the-point idea of what's in the corpus and what to be expected from the markup.

Right now we're systematically correcting just the worst errors. In the future, I would also systematically recode "End of act/End of play" passages as ```<trailer>``` like you proposed (these remarks shouldn't even be comprised in ```<sp>``` to begin with). Feel free to collect other anomalies, because now is the time to take care of it. ;)

**Comment by nilsreiter** [comment]
Thanks for the update! We don't really want to wait, so I guess we just correct the stuff as we find it and try to merge later on.

The fact that you removed superfluous `<div>`-tags actually makes our forks not easy to re-merge (but the wiki page is a good record!)

**Comment by lehkost** [comment]
If it were only the superfluous ```<div>``` tags… I think my full account after finishing work on GerDraCor will problematise the kind of corpus we've been working with the past years. :) The plan is to re-run all scripts of the past to give an impression of the level of inaccuracy we bought into by relying on the old TG corpus.

**Comment by pagelj** [comment]
This has been fixed in the newest GerDraCor release https://github.com/dracor-org/gerdracor/commit/f8cdf7b197143c5b3ef362fa1da5275772663b82
